/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.repository.WeatherRepository

fun main() {
    val apiKey = ""
    val city = "Jakarta"
    val repository = WeatherRepository()
    repository.getWeatherForecast(city, apiKey)
}
